### ISSUE TITLE
[TS-325] Error posting data to endpoint

### ISSUE THREAD

**Issue by lg-qinhaoran** [codacy/codacy-analysis-cli-action#111]
I'm using SpotBugs to analysis java code, but I get an error in GitHub Action logs:

Analysis complete
04/06 04:11:34 ERROR c.c.a.c.clients.CodacyClient:129 - Error posting data to endpoint /gh/xxx/xxx/commit/xxx/issuesRemoteResults 
io.circe.ParsingFailure: expected json value got '<!DOCT...' (line 1, column 1)

Does anyone know why what is?

**Comment by DMarinhoCodacy** [comment]
Hello @lg-qinhaoran 

Thanks for reporting this.

Can you provide the whole output? You can send us to support@codacy.com.

Kind regards,
David Marinho
