### ISSUE TITLE
[TS-358] line 8: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by abhi-markan** [codacy/codacy-analysis-cli-action#113]
## Introduction
Ever since latest merge, all Codacy GHAs are failing with same error messages (testes on numerous public repositories).

Error: `line 8: syntax error: unexpected end of file`

```
Run echo "CODACY_BASE_URL_OR_DEFAULT=$(if [  ]; then echo ""; else echo "https://api.codacy.com/"; fi)" >> $GITHUB_ENV
  echo "CODACY_BASE_URL_OR_DEFAULT=$(if [  ]; then echo ""; else echo "https://api.codacy.com/"; fi)" >> $GITHUB_ENV
  echo "OWNER_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)" >> $GITHUB_ENV
  echo "REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV
  echo "ORGANIZATION_PROVIDER=$(if [ "$GITHUB_SERVER_URL" == "https://github.com" ]; then echo "gh"; else echo "ghe"; fi)" >> $GITHUB_ENV
  echo "COMMIT_SHA=$(if [ pull_request == "pull_request" ]; then echo "0ad579b700a2694690164bd5a80b71cc0e6891fe"; else echo "d72a73cd0a4ca22ec081e4d3[12](https://github.com/UK-Export-Finance/exip/actions/runs/4833369723/jobs/8613291873?pr=451#step:3:13)674652acbbb5ca"; fi)" >> $GITHUB_ENV
  if [ -n "" ]; then
    echo "SKIP_CONTAINER_ENGINE_CHECK=" >> $GITHUB_ENV
    
    e08742c6-7c79-42f1-8745-7acba0104a6e.sh: line 8: syntax error: unexpected end of file
```

**Comment by dwertent** [comment]
[I get the same](https://github.com/dwertent/kubescape/actions/runs/4845645989/jobs/8634686040) :(

[Here is my Github action](https://github.com/dwertent/kubescape/commit/f4841068a774461751eea0ad617e02e88ba31561).

**Comment by zethuman** [comment]
\+ 1 same error

**Comment by dan-istoc-k24** [comment]
i have the same issue, is there any temporary fix?

**Comment by DMarinhoCodacy** [comment]
Hello all,
We found an issue in the latest changes, and we already fix it. Can you please re-run your jobs?
Thanks for the tip @bjarkebm ! 
Support team @ Codacy

**Comment by McPringle** [comment]
I can confirm it works! Thank you very much for your fast fix and for providing this service!
