### ISSUE TITLE
[TS-401] attempts to disable individual tools are fully ignored

### ISSUE THREAD

**Issue by mirabilos** [codacy/codacy-analysis-cli-action#117]
Due to the amount of issues with these tools, I tried disabling them per the documentation…

```
$ cat .codacy.yml 
---
engines:
  pylint:
    # pylintpython3 is used instead
    enabled: false
  tsqllint:
    # for Microsoft only
    enabled: false
```

… but this seems to be fully ignored.

**Comment by madalenamelo** [comment]
Hi @mirabilos,

Thank you for reaching out to our community! Unfortunately, it is not currently possible to use the `.codacy.yml` file to disable tools, instead, you must disable tools using the [Code patterns page](https://docs.codacy.com/repositories-configure/configuring-code-patterns/).

You can find this information on our official documentation [here](https://docs.codacy.com/repositories-configure/codacy-configuration-file/).

Please free to add any other questions or information here.

Regards,
Madalena

**Comment by mirabilos** [comment]
madalenamelo dixit:

>Thank you for reaching out to our community! Unfortunately, it is not
>currently possible to use the `.codacy.yml` file to disable tools,
>instead, you must disable tools using the [Code patterns
>page](https://docs.codacy.com/repositories-configure/configuring-code-patterns/).

I don’t have such a page, I just have the GH Action.

**Comment by madalenamelo** [comment]
@mirabilos thank you for clarifying! However, it's not possible to disable tools using the GH Action alone as disabling tools needs to be done on the Codacy UI.
