### ISSUE TITLE
[TCE-1040] Default value for parameter 'registry-address' breaking default behavior

### ISSUE THREAD

**Issue by KB1RMA** [codacy/codacy-analysis-cli-action#130]
It looks like the new `registry-address` parameter just introduced in #129 has broken the default behavior of this action. Since the value is set to "gh" by default - it now tries to pull docker images from `ghcodacy` namespace rather than `codacy`

Logs from an actions run using `codacy/codacy-analysis-cli-action@v4`

```
Status: Downloaded newer image for codacy/codacy-analysis-cli:7.9.10
07/11 12:16:40 ERROR c.c.a.c.a.CodacyPluginsAnalyser:31 - Failed analysis for pmd 
java.lang.Throwable: 
Docker exited with code 125
stdout: 
stderr: Unable to find image 'ghcodacy/codacy-pmd:3.13.13' locally
docker: Error response from daemon: pull access denied for ghcodacy/codacy-pmd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

Unfortunately this isn't avoidable since if we pass in an empty value to the action, it reverts back to the default

**Comment by hjrocha** [comment]
Just pushed a PR with a fix. Thanks for the heads up

**Comment by KB1RMA** [comment]
@hjrocha just confirmed it's fixed for us. Appreciate the quick turnaround
