### ISSUE TITLE
[CY-3681] Can't specify absolute path

### ISSUE THREAD

**Issue by IntelBear** [codacy/codacy-analysis-cli-action#32]
I'm trying to use this action and providing a directory to start from as seen in the documentation, but it's unable to accept absolute path that I'm giving by passing in ${{ github.ref }}/src (src is at the top level of my repo). What's the proper syntax to pass an absolute path into the directory option?

**Comment by josemiguelmelo** [comment]
Hi @IntelBear ,

Our codacy-analysis-cli is expecting the directory to be the root of the repository. So, passing a folder that is not the root of your repository to the `directory` parameter will make the CLI fail.

Also, it seems the environment variable that contains the workspace directory path is GITHUB_WORKSPACE (https://docs.github.com/en/actions/reference/environment-variables).

**Comment by josemiguelmelo** [comment]
Hi!
I'm closing the issue. Feel free to re-open it if you need any more help on this 🙂
Thanks,

**Comment by gjermundgaraba** [comment]
Does the directory parameter make any sense then for the github action? If not, might be good to document under "Extra configurations".
