### ISSUE TITLE
[CY-3786] Action generates invalid sarif entries

### ISSUE THREAD

**Issue by wirew0rm** [codacy/codacy-analysis-cli-action#34]
Yesterdays new v2.0.0 release led to build problems with the Github Code Scanning Integration as described in the README.md.

The sarif file generated by the codacy action generates invalid sarif files which fail the upload-sarif step with the error: 
`Error details: instance.runs[2].results[84].locations[0].physicalLocation.region.startLine must have a minimum value of 1`

See e.g https://github.com/GSI-CS-CO/chart-fx/runs/1963883735?check_suite_focus=true#step:11:20

We are using the master version of both actions, previously successful runs of the action also fail with that same exception if they are rerun.

**Comment by lolgab** [comment]
Hi @wirew0rm,
Can you try the version `2.0.1` that I just released? It should fix the problem.

**Comment by wirew0rm** [comment]
I just checked, this fixed the failing builds. Thank you for the fast response and fix!

**Comment by lolgab** [comment]
Happy that your problem was solved @wirew0rm!
