### ISSUE TITLE
[CY-3974] Apply code analysis only to PR relative files

### ISSUE THREAD

**Issue by firegloves** [codacy/codacy-analysis-cli-action#36]
Hi, I'm trying to integrate Codacy into my CI/CD process.
What I'm trying to do is to apply code analysis only to the files relative to the current Pull Request but I can't get it working.

I tried by fixing a particular issue reported by Codacy in a dedicated branch and then by creating a PR. In the action logs, I get a list of issues, but I would like to address them progressively without changing the whole codebase in a single step.

There is a way to accomplish my goal or isn't it supported?

**Comment by pedrocodacy** [comment]
Hi @firegloves,

Yes you can! But with extra steps: 

Unfortunately this GitHub action only runs our code analysis, it is not able to keep that kind of state about previous issues that were detected by itself. 

You can however integrate your repositories with our main product (codacy.com) where you can log-in with your GitHub account and quickly setup your repository. Using it this way, Codacy will be able to provide you with: 

- storage for the state of previously detected issues, making them not show in new PRs after the first analysis of your main branch 
- a UI to visualise and to manage these issues (ignore false positives, manage tools and patterns that are being applied)

If you choose to integrate with our main product, we will automatically run analysis for you without the need for the CI by default. You can still opt in to use this Github Action in your CI/CD to generate the analysis data that Codacy will use - just follow steps 1 through 3 in https://github.com/codacy/codacy-analysis-cli-action#integration-with-codacy-for-client-side-tools).

**Comment by machadoit** [comment]
Closing it for now, @firegloves feel free to reopen
