### ISSUE TITLE
[CY-4089] unable to find version `master` for codeql-action

### ISSUE THREAD

**Issue by Siddhant-K-code** [codacy/codacy-analysis-cli-action#38]
![image](https://user-images.githubusercontent.com/55068936/113126760-98d5c300-9235-11eb-964f-2b8c460bf63a.png)

I think this issue occurs happens because [codeql-action](https://github.com/github/codeql-action) is not using `master` anymore, they are using `main`.

To fix this, we have to update it from all our Documentation & `README`

I can work on this.

**Comment by franciscodua** [comment]
Hey @Siddhant-K-code 

You are probably right.
And if you want to pick this issue up we would appreciate it.

Let us know if you have the availability to do it and send us a PR whenever you can. Otherwise, we can look into it 👍

**Comment by Siddhant-K-code** [comment]
I will make a PR by tomorrow.
