### ISSUE TITLE
[CY-4093] science

### ISSUE THREAD

**Issue by rochard1** [codacy/codacy-analysis-cli-action#39]
// Suppress all the diagnostics for the line
  Foo(int param); // NOLINT

  // Consider explaining the motivation to suppress the warning.
  Foo(char param); // NOLINT: Allow implicit conversion from `char`, because <some valid reason>.

  // Silence only the specified checks for the line
  Foo(double param); // NOLINT(google-explicit-constructor, google-runtime-int)

  // Silence only the specified diagnostics for the next line
  // NOLINTNEXTLINE(google-explicit-constructor, google-runtime-int)
  Foo(bool param);
};

**Comment by rochard1** [comment]
google-runtime-int

**Comment by franciscodua** [comment]
Hey @rochard1 

If I understood this issue correctly, you are suggesting we support some ways to suppress issues.
However, Codacy doesn't analyze the code directly. We rely on open-source tools that do it and collect the results.

But these tools we use sometimes support that impression. If you are interested in a specific tool let us know, or look for suppression mechanisms in their documentation.

If I completely misread this issue, let us know too 😅

**Comment by franciscodua** [comment]
I'm closing this issue. Feel free to re-open it or create a new one if you have any question
