### ISSUE TITLE
[CY-4155] What is the license of this repository ?

### ISSUE THREAD

**Issue by Cedric-Magnan** [codacy/codacy-analysis-cli-action#41]
codacy-analysis-cli is under AGPL-3.0 License, does it mean that this repository should also be under AGPL-3.0 License ?
If yes, could you add the license to this repository in order for us to use this action for private use ?

**Comment by franciscodua** [comment]
Hey @Cedric-Magnan 
We just added an Apache 2.0 license to the repository. Thanks for pointing the lack of license.

That license should be good enough for your needs but let us know if something doesn't work for you by re-opening this issue
