### ISSUE TITLE
[CY-4226] Using this action with .NET Core projects results in the scanner detecting issues that should not exist.

### ISSUE THREAD

**Issue by AraHaan** [codacy/codacy-analysis-cli-action#52]
So I use this action for my .NET Core projects. These projects rely on the .NET SDK to generate the ``AssemblyInfo.cs`` file with metadata like the assembly versions, the Neutral resources language, etc.

Because of the fact the workflow autogenerated raises this issue, is it because the workflow does not at least run ``dotnet restore`` or something on the code?

As such I have since changed the structure of my workflows so then there is the added fact that my other workflows would want to invoke my automerge workflow so then it tries to automerge BEFORE the security checks return from the codacy security scanning workflow resulting in automerge not happening automatically after it passes.

Because of that I decided to remove the automerge workflow for using mergify that seems to support the same thing (but enhances it with comments on the pull requests), however since the build workflow will add the ``automerge`` label I think that workflow should do the security scanning as well so I have fewer workflows to maintain. Hopefull it will resolve this issue. If it does I will automatically close it, if not I would like some way to fix it to only provide actual security issues on my project's security tab.

**Comment by franciscodua** [comment]
Hi @AraHaan 
>is it because the workflow does not at least run dotnet restore or something on the code?

Correct, this action does not run `dotnet` commands or change your code in any way.

Did you have success solving this problem?

If I understood correctly, you want to merge your PR after your checks run and Codacy finishes its analysis. Maybe the branch protection rules in Github can help you with this (https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule). You make the Codacy results a required step in your PRs.

Let us know if this helped.

**Comment by AraHaan** [comment]
having it use ``setup-dotnet`` and then having it also run ``dotnet restore`` seems to work actually.

Another thing I realized as well is that on the scanning I forgot to pass in the access token for codacy that I set on the organization level so then it was ignoring the settings set in the actual project there.
