### ISSUE TITLE
[CY-4277] Rename master to main.

### ISSUE THREAD

**Issue by AraHaan** [codacy/codacy-analysis-cli-action#57]
I would like for master to be renamed to main because a lot of other github actions I use do such.

**Comment by franciscodua** [comment]
Hi @AraHaan 

Unfortunately, changing that at this point will be a breaking change and we need to work on a transition plan for current users.

We'll keep it in our internal backlog but at the moment it's not a high priority issue.

I'll close this. But feel free to re-open it or create a new one if you have further questions or suggestions.

**Comment by AraHaan** [comment]
I think this can be miticated by having ``master`` be a tag that gets updated with ``main`` when ``master`` is renamed to ``main`` (it should be simple to set it up).

**Comment by AraHaan** [comment]
@franciscodua did you guys look into what I said in October (Where master can be renamed to main and have ``master`` be a floating tag that gets updated every time the renamed branch gets pushed to)?
