### ISSUE TITLE
[CY-4520] Sorry, we couldn't find this file in the repository.

### ISSUE THREAD

**Issue by leleliu008** [codacy/codacy-analysis-cli-action#61]
[relavant project](https://github.com/leleliu008/C/actions/runs/940070200/workflow)

![image](https://user-images.githubusercontent.com/3040852/122168343-bf0f1480-ceae-11eb-8f7c-dc2af41f0402.png)

**Comment by zetroot** [comment]
Action is great, but it cant be used from github as for this issue

**Comment by AraHaan** [comment]
I agree this needs to be fixed ASAP I am also affected by this so I can see for where in the code it's triggered for as sometimes there are false positives all because it's used in tests.

**Comment by jllopes** [comment]
Hi @leleliu008.

I just merged a PR that should fix this problem, can you please test it on your side and tell us if it gets solved?

Thanks.

**Comment by leleliu008** [comment]
@jllopes  it works now. Thank you for your job.
