### ISSUE TITLE
[CY-4835] Document way to cache the docker containers downloaded by the action.

### ISSUE THREAD

**Issue by AraHaan** [codacy/codacy-analysis-cli-action#64]
I would really like it if one would know what to do if they want their Code analysis workflow file to cache the docker containers that said workflow downloads so it can speed up future analysis's.

**Comment by machadoit** [comment]
Hi @AraHaan that sounds interesting, but it does not easy to achieve using GitHub actions. We would need to check some of the approaches mentioned here https://github.com/actions/cache/issues/31.

That said, I will add this as an internal feature request, but will leave this open, in case of you or someone else has an interesting approach that is clear and reproducible that we could then document.

**Comment by AraHaan** [comment]
I would like to know how this was completed if possible.
