### ISSUE TITLE
[CY-4991]  invalid DOCKER_HOST must be unset or unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by mickelglobbins** [codacy/codacy-analysis-cli-action#66]
The codacy-analysis-cli-action execution fails when DOCKER_HOST is a different socket value than `unix:///var/run/docker.sock`.

```
Run codacy/codacy-analysis-cli-action@master
+ '[' '' == true ']'
+ echo 'Skipping GoSec'
Skipping GoSec
+ '[' '' == true ']'
+ echo 'Skipping StaticCheck'
Skipping StaticCheck
+ '[' -n '' ']'
+ echo 'Skipping Clang Tidy'
Skipping Clang Tidy
+ '[' -n '' ']'
+ echo 'Skipping Faux Pas'
Skipping Faux Pas
--2021-09-13 21:59:35--  https://raw.githubusercontent.com/codacy/codacy-analysis-cli/7.0.5/bin/codacy-analysis-cli.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3107 (3.0K) [text/plain]
Saving to: ‘STDOUT’

     0K ...                                                   100% 39.9M=0s

2021-09-13 21:59:35 (39.9 MB/s) - written to stdout [3107/3107]

We encountered a problem with your Docker setup:
  > invalid DOCKER_HOST=unix:///run/user/<REDACTED>/docker.sock, must be unset or unix:///var/run/docker.sock

Please check https://github.com/codacy/codacy-analysis-cli for alternative instructions.

Error: Process completed with exit code 3.
```

It looks like the [codacy-analysis-cli.sh](https://github.com/codacy/codacy-analysis-cli/blob/master/bin/codacy-analysis-cli.sh#L20) is explicitly checking the value of `DOCKER_HOST`.

**Comment by machadoit** [comment]
Hi  @mickelglobbins can you share a bit about your use case, and why you need it to be different? We do have some restrictions that we require to be set as `unix:///var/run/docker.sock`.

Share whatever information you can on your use case, so I can bring it to the team, to consider adding it to our backlog, as it may not be a straightforward change.

**Comment by machadoit** [comment]
Closing the issue for now, as we don't have any use case at the moment that we are looking to support changing DOCKER_HOST
