### ISSUE TITLE
[CY-5234] Preview unavailable in Github code scanning results

### ISSUE THREAD

**Issue by phw** [codacy/codacy-analysis-cli-action#67]
We added this action to https://github.com/metabrainz/picard/blob/master/.github/workflows/codacy-analysis.yml . Analysis triggers and results show up in Github code scanning results, but the preview is not available.

It looks like this is because of wrong paths in the uploaded results. The paths displayed are like `file:///codacy/picard/ui/metadatabox.py `, whereas the paths reported e.g. by CodeQL are just `picard/ui/metadatabox.py`.

Is this a bug or a configuration issue on our side?

See also this screenshot:

![grafik](https://user-images.githubusercontent.com/29852/141297838-f78be12c-2ae2-4adf-9bd9-dd4e5da6bf0a.png)

**Comment by machadoit** [comment]
Seems to be related to https://github.com/codacy/codacy-analysis-cli-action/issues/61 that should be fixed on the current version of the action. 

Please make sure that you are using the [latest version](https://github.com/marketplace/actions/codacy-analysis-cli). You can use `@master`, or the current `4.0.0`. Let us know if that fixes the problem for you.
