### ISSUE TITLE
[CY-6443] The  gosec version 1.07 isn't compatible with the go 1.18

### ISSUE THREAD

**Issue by aujinj** [codacy/codacy-analysis-cli-action#84]
If you use the go with 1.18 and enable goSec, this will throw errors 
internal error: package "<...>" without types was imported from "command-line-arguments"

https://giters.com/securego/gosec/issues/797

The easy fix is to update the gosec from 1.7.0 to version v2.12.0 or later
https://github.com/codacy/codacy-analysis-cli-action/blob/9cc325a3a85ab23467a7cf32b9e6223927c206f1/action.yml#L120

**Comment by prcr** [comment]
Hello @aujinj, and thank you for submitting this issue.

Currently, the latest Go version that we support is 1.17.13, but we'll be looking into updating [codacy/codacy-gosec](https://github.com/codacy/codacy-gosec) so that it starts supporting Go 1.18.

We'll let you know when we have an update.

**Comment by stefanvacareanu7** [comment]
Hi @aujinj,

I've updated the gosec version to v2.13.1.

Can you check if it fixes your issue?

Best,
Stefan
