### ISSUE TITLE
[TS-170] misdetects .sql as TSQL

### ISSUE THREAD

**Issue by mirabilos** [codacy/codacy-analysis-cli-action#97]
I get an error because my .sql file is for PostgreSQL and contains PL/pgSQL and your tool misdetects it as Microsoft TSQL and lacks an override

**Comment by codacy-vrhpires** [comment]
Codacy chooses the tools based strictly on extensions. Currently there are 3 tools for .sql files:
- SQLint
- PMD
- TSQLint

You can choose the specific tools being used with a [Codacy configuration file](https://docs.codacy.com/repositories-configure/codacy-configuration-file/).

**Comment by mirabilos** [comment]
Vítor Pires dixit:

>Codacy chooses the tools based strictly on extensions. Currently there
>are 3 tools for .sql files:
>- SQLint
>- PMD
>- TSQLint

Huh.

SQLint says it supports PostgreSQL, which would work.

>You can choose the specific tools being used with a [Codacy
>configuration
>file](https://docs.codacy.com/repositories-configure/codacy-configuration-file/).

How? The linked page doesn’t explain.

Currently, I have:

$ cat .codacy.yml
---
engines:
  pylint:
    # pylintpython3 is used instead
    enabled: false
  tsqllint:
    # for Microsoft only
    enabled: false

This is seemingly ignored…

The page doesn’t say how to choose the tool for the extension.

bye,
//mirabilos
-- 
Infrastrukturexperte • Qvest Digital AG
Am Dickobskreuz 10, D-53121 Bonn • https://www.qvest-digital.com/
Telephon +49 228 54881-393 • Fax: +49 228 54881-235
HRB AG Bonn 18196 • USt-ID (VAT): DE274355441
Vorstand: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg
Vorsitzender Aufsichtsrat: Peter Nöthen
